### ISSUE TITLE
Recent 4chan X updates broke the style

### ISSUE THREAD

**Issue by welpo** [RiDeag/Stilig#9]
No settings were changed on my end. I can't tell for sure which version broke it.
- From the screenshots you can see the list of boards is now horizontal and over the content of the site.
  ![ss 2015-03-31 at 12 44 56](https://cloud.githubusercontent.com/assets/6399341/6949261/b72da0a8-d8b3-11e4-9463-09fed8e5d285.png)
- The Watched Threads are either invisible or I lost them.
- The favicon doesn't update when you scroll to the bottom, neither does the tab title.
- Settings / Catalog top bar is broken as well, cutting off the words.
  ![ss 2015-04-01 at 09 12 09](https://cloud.githubusercontent.com/assets/6399341/6949354/387148d6-d8b4-11e4-9c26-8d63546a5904.png)
- The options menu to hide/report... a post / thread will fall behind the background of the other posts, making it not visible.

![ss 2015-04-01 at 09 11 56](https://cloud.githubusercontent.com/assets/6399341/6949356/3b790d34-d8b4-11e4-8e45-24bd448d15e9.png)

I'm not sure if there are more issues, these are the ones I've noticed for now.

**Comment by ghost** [comment]
I recently updated [my fork](https://github.com/mudanaku/Stilig/blob/master/Stilig.css), have you tried it?

**Comment by welpo** [comment]
It fixed everything except the favicon / title updating with new/read posts.

**Comment by ghost** [comment]
- The favicon doesn't update when you scroll to the bottom, neither does the tab title.

[Seems to work for me?](http://a.pomf.se/fiispn.webm)

**Comment by welpo** [comment]
I think the problem is I was applying two different CSS to the site (different versions of this style): one through 4chan X and another through Stylish add-on.
Resetting 4chan X settings fixed it (since I only used Stylish), and removing the Stylish CSS and using only 4chan X CSS worked too.
